version: "3.7"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME-postgres}
      - POSTGRES_USER=${DATABASE_USER-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD-postgres}
  web:
    build: .
    environment:
      - DATABASE_NAME=${DATABASE_NAME-postgres}
      - DATABASE_USER=${DATABASE_USER-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD-postgres}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db